server:
  port: 8761 # 端口
spring:
  application:
    name: eureka-server # 服务名称
eureka:
  instance:
    appname: eureka-server
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # 默认服务注册中心地址, 多个使用 ',' 隔开
    register-with-eureka: false  #是否注册, 默认值 true, 由于这个项目作为 eureka 的注册中心使用, 注册自己会报错, 配置其他注册中心地址不会报错
    fetch-registry: false  #是否从其他Eureka服务端获取注册信息，默认为true。如过是单台服务器可以设置为false
  server:
    eviction-interval-timer-in-ms: 10000  #注册中心清理无效节点的时间间隔, 默认为 60000L , 单位毫秒 ms
  dashboard:
    path: /eureka-ui
